export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: '/api/v1/auth/login',
    REFRESH: '/api/v1/auth/refresh',
    LOGOUT: '/api/v1/auth/logout',
    ME: '/api/v1/auth/me',
  },
  UPLOAD: '/api/v1/upload',
  HEALTH: '/api/v1/health',
  CATEGORIES: {
    BASE: '/api/v1/categories',
    DETAIL: (id: string) => `/api/v1/categories/${id}`,
    TRANSLATION: (id: string) => `/api/v1/categories/${id}/translation`,
  },
  PRODUCTS: {
    BASE: '/api/v1/products',
    DETAIL: (id: string) => `/api/v1/products/${id}`,
    RELATED: (id: string) => `/api/v1/products/${id}/related`,
    VIEW: (id: string) => `/api/v1/products/${id}/view`,
    COPY: (id: string) => `/api/v1/products/${id}/copy`,
    TRANSLATION: (id: string) => `/api/v1/products/${id}/translation`,
  },
  PROJECTS: {
    BASE: '/api/v1/projects',
    DETAIL: (id: string) => `/api/v1/projects/${id}`,
    TRANSLATION: (id: string) => `/api/v1/projects/${id}/translation`,
  },
  JOBS: {
    BASE: '/api/v1/jobs',
    DETAIL_SLUG: (slug: string) => `/api/v1/jobs/${slug}`,
    DETAIL_ID: (id: string) => `/api/v1/jobs/${id}`,
    TRANSLATION: (id: string) => `/api/v1/jobs/${id}/translation`,
  },
  LEADS: {
    BASE: '/api/v1/leads',
    DETAIL: (id: string) => `/api/v1/leads/${id}`,
    STATUS: (id: string) => `/api/v1/leads/${id}/status`,
  },
  DASHBOARD: {
    STATS: '/api/v1/dashboard/stats',
  },
  SETTINGS: {
    SYSTEM: '/api/v1/settings/system',
    SYSTEM_KEY: (key: string) => `/api/v1/settings/system/${key}`,
    SLOGANS: '/api/v1/settings/slogans',
    SLOGANS_DETAIL: (id: string) => `/api/v1/settings/slogans/${id}`,
    TIMELINES: '/api/v1/settings/timelines',
    TIMELINES_DETAIL: (id: string) => `/api/v1/settings/timelines/${id}`,
    BANNERS: '/api/v1/settings/banners',
    BANNERS_DETAIL: (id: string) => `/api/v1/settings/banners/${id}`,
  },
  CONTACT_SETTING: {
    BASE: '/api/v1/contact-setting',
  },
  FOOTER_SETTING: {
    BASE: '/api/v1/footer-setting',
  },
  ABOUT: {
    PROFILE: '/api/v1/about/profile',
    COMPANY_INFO: '/api/v1/about/company-info',
    COMPANY_INFO_DETAIL: (id: string) => `/api/v1/about/company-info/${id}`,
    FACILITIES: '/api/v1/about/facilities',
    FACILITY_DETAIL: (id: string) => `/api/v1/about/facilities/${id}`,
    HISTORY_EVENTS: '/api/v1/about/history-events',
    HISTORY_EVENT_DETAIL: (id: string) => `/api/v1/about/history-events/${id}`,
    LOCATIONS: '/api/v1/about/locations',
    LOCATION_DETAIL: (id: string) => `/api/v1/about/locations/${id}`,
    LOCATIONS_ORDER: '/api/v1/about/locations/order',
  },
  USERS: {
    BASE: '/api/v1/users',
    ADMIN: '/api/v1/users/admin',
    RESET_PASSWORD: (id: string) => `/api/v1/users/${id}/reset-password`,
    KICK: (id: string) => `/api/v1/users/${id}/kick`,
    DELETE: (id: string) => `/api/v1/users/${id}`,
  },
} as const;
